name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  EM_VERSION: 1.39.18
  EM_CACHE_DIR: 'emsdk-cache'

jobs:
  build_wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup cache for Emscripten
      id: cache-system-libraries
      uses: actions/cache@v2
      with:
        path: ${{env.EM_CACHE_DIR}}
        key: ${{env.EM_VERSION}}-${{ runner.os }}
    - uses: mymindstorm/setup-emsdk@v6
      with:
        version: ${{env.EM_VERSION}}
        actions-cache-folder: ${{env.EM_CACHE_DIR}}
    - name: Setup cache for game data
      id: cache-game-data
      uses: actions/cache@v2
      with:
        path: DUKE2
        key: duke2-shareware
    - name: Fetch game data
      run: bash -c '[ -d DUKE2 ] || (wget https://archive.org/download/msdos_DUKE2_shareware/DUKE2.zip && unzip DUKE2.zip)'
    - name: Run CMake
      run: emcmake cmake -H. -Bbuild_wasm -DCMAKE_BUILD_TYPE=Release -DWARNINGS_AS_ERRORS=Off -DWEBASSEMBLY_GAME_PATH=$(pwd)/DUKE2
    - name: Build
      run: make -j2 -Cbuild_wasm
